export const SYNNICAL_APPS = [
  { id: "discover", label: "Search", aliases: ["find", "global search"], authOnly: true },
  { id: "browser", label: "Browser", aliases: ["web", "proxy"] },
  { id: "games", label: "Games", aliases: ["gaming", "cloud games"] },
  { id: "chat", label: "Chat", aliases: ["messages", "dm"] },
  { id: "friends", label: "Friends", aliases: ["people"], authOnly: true },
  { id: "spaces", label: "Spaces", aliases: ["rooms", "hangout"], authOnly: true },
  { id: "movies", label: "SynnFlix", aliases: ["movies", "shows", "watch"] },
  { id: "music", label: "Music", aliases: ["songs", "playlist"] },
  { id: "calls", label: "Calls", aliases: ["voice", "video"], authOnly: true },
  { id: "ai", label: "AI Assistant", aliases: ["assistant", "synn ai"] },
  { id: "youtube", label: "YouTube", aliases: ["video", "youtube video"] },
  { id: "geforce-now", label: "GeForce NOW", aliases: ["nvidia", "cloud gaming", "gfn"] },
  { id: "files", label: "Synnical Files", aliases: ["files", "downloads", "screenshots", "explorer"], authOnly: true },
  { id: "automations", label: "Automations", aliases: ["routines", "rules"], authOnly: true },
  { id: "temp-mail", label: "Temp Mail", aliases: ["mail", "temporary email"] },
  { id: "shop", label: "Shop", aliases: ["cosmetics"], authOnly: true },
  { id: "market", label: "Marketplace", aliases: ["trade", "resale"], authOnly: true },
  { id: "creator", label: "Creator Studio", aliases: ["create", "cosmetic editor"], authOnly: true },
  { id: "developer", label: "Developer", aliases: ["api", "tokens"], authOnly: true },
  { id: "profile", label: "Profile", aliases: ["identity", "personas"], authOnly: true },
  { id: "settings", label: "Settings", aliases: ["preferences", "security", "privacy"], authOnly: true },
] as const
