import test from "node:test"
import assert from "node:assert/strict"
import { existsSync, readFileSync } from "node:fs"

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8")

test("game focus cannot hide Synnical chrome outside Games", () => {
  const shell = read("src/components/app-shell.tsx")
  assert.match(shell, /const gameFocusVisible = gameFocus && \(panel === "games" \|\| panel === "geforce-now"\)/)
  assert.match(shell, /!gameFocusVisible && <TopBar/)
  const games = read("src/components/games-panel.tsx")
  assert.doesNotMatch(games, /group\/game fixed inset-0 z-\[9999\]/)
  assert.match(games, /group\/game absolute inset-0 z-20/)
  assert.match(games, /sessionState\.phase === "active" && gameFullscreen && !inputReleased/)
  assert.doesNotMatch(games, /setCatalogError\(`\[\$\{failure\.code\}\]/)
})

test("SynnFlix player URL is stable while timeupdate progress is saved", () => {
  const source = read("src/components/synnflix-panel.tsx")
  assert.match(source, /const playerUrl = useMemo\(/)
  assert.match(source, /key=\{`\$\{playerRevision\}:\$\{playerUrl\}`\}/)
  assert.doesNotMatch(source, /if \(player\) \{\s*const playerUrl = buildPlayerUrl/)
  assert.match(source, /Copy invite/)
  assert.match(source, /Paste the watch party invite code/)
  assert.doesNotMatch(source, /Share this party ID/)
})

test("connections are account-scoped server data, not browser-global profile data", () => {
  const connections = read("src/lib/connections.ts")
  assert.match(connections, /fetch\("\/api\/profile\/connections"/)
  assert.match(connections, /export function loadLegacyConnections/)
  assert.match(connections, /export function clearLegacyConnections/)
  const settings = read("src/components/settings-panel.tsx")
  assert.match(settings, /\}, \[user\?\.id\]\)/)
  assert.match(settings, /Import to @/)
  const modal = read("src/components/user-profile-modal.tsx")
  assert.doesNotMatch(modal, /loadConnections/)
  assert.match(modal, /const connections = data\?\.connections \|\| \[\]/)
  const route = read("src/app/api/profile/connections/route.ts")
  assert.match(route, /where: \{ id: me\.id \}/)
  const schema = read("prisma/schema.prisma")
  assert.match(schema, /connectionsJson\s+String\s+@default\("\[\]"\)/)
})

test("credits start at zero and global reset has a durable exactly-once marker", () => {
  const schema = read("prisma/schema.prisma")
  assert.match(schema, /coins\s+Int\s+@default\(0\)/)
  assert.match(schema, /model SystemMigration/)
  const register = read("src/app/api/auth/register/route.ts")
  assert.match(register, /coins: 0/)
  assert.doesNotMatch(register, /signup_bonus/)
  assert.doesNotMatch(register, /amount: 500/)
  const reset = read("scripts/one-time-coin-reset.ts")
  assert.match(reset, /2026-08-17-global-credit-reset-v1/)
  assert.match(reset, /type: "GLOBAL_RESET"/)
  assert.match(reset, /beforeBalance: before/)
  const installer = read("install-full.sh")
  assert.match(installer, /scripts\/one-time-coin-reset\.ts/)
  assert.match(installer, /GLOBAL_CREDIT_RESET_VERIFIED/)
  assert.match(installer, /RESET_MARKER_BEFORE/)
  assert.match(installer, /current earned balances preserved unchanged/)
})

test("normal UI avoids raw proxy timeout codes and unexplained watch-party ids", () => {
  const browser = read("src/components/browser-panel.tsx")
  assert.doesNotMatch(browser, /\[PROXY_NAVIGATION_TIMEOUT\]/)
  const movies = read("src/components/synnflix-panel.tsx")
  assert.doesNotMatch(movies, /Watch party ID/)
})

test("staff credit adjustments exist, obey hierarchy, and are audited", () => {
  const route = read("src/app/api/moderation/credits/route.ts")
  assert.match(route, /rank\[actor\.role\]/)
  assert.match(route, /rank\[target\.role\]/)
  assert.match(route, /type: "STAFF_ADJUSTMENT"/)
  assert.match(route, /creditAudit\.create/)
  const panel = read("src/components/staff-accounts-panel.tsx")
  assert.match(panel, /Add credits/)
  assert.match(panel, /Remove credits/)
})


test("watch parties never steal the provider play button", () => {
  const source = read("src/components/synnflix-panel.tsx")
  assert.match(source, /buildPlayerUrl\(player, \{ progress: syncedProgress, autoplay: true \}\)/)
  assert.doesNotMatch(source, /\[player, syncedProgress, partyHeld\]/)
  assert.doesNotMatch(source, /partyHeld \? <div className="grid h-\[600px\]/)
  assert.match(source, /Sync to host/)
  assert.match(source, /Reload player/)
  assert.match(source, /playing: playerPlayingRef\.current/)
})

test("game sessions reconcile stale active rows and heartbeat the live session", () => {
  const route = read("src/app/api/features/games/route.ts")
  assert.match(route, /GAME_SESSION_STALE_MS = 120_000/)
  assert.match(route, /reconcileGameSessions/)
  assert.match(route, /session\.id !== user\.gameStatusSessionId/)
  assert.match(route, /closeGameSessions\(user\.id, stale, "interrupted"\)/)
  assert.match(route, /action === "session-heartbeat"/)
  assert.match(route, /previous\.length.*closeGameSessions/s)
  const panel = read("src/components/games-panel.tsx")
  assert.match(panel, /trackedSessionStartRef/)
  assert.match(panel, /session-heartbeat/)
  assert.match(panel, /30_000/)
  assert.match(panel, /keepalive: true/)
  assert.match(panel, /result: "page-exit"/)
})

test("cloud game capture is immersive and management controls stay outside fullscreen", () => {
  const games = read("src/components/games-panel.tsx")
  const embed = read("stratus/public/e.html")
  assert.match(games, /navigator as Navigator & \{ keyboard\?: \{ lock\?:/)
  assert.match(games, /nav\.keyboard\?\.lock\?\.\(\)/)
  assert.match(games, /document\.addEventListener\("fullscreenchange", onFullscreenChange\)/)
  assert.match(games, /SYNNICAL_GAME_RELEASE_INPUT/)
  assert.match(games, /if \(gameFullscreen && !inputReleased\)/)
  assert.match(games, /Reconnects performed from the released\/non-fullscreen toolbar/)
  assert.match(games, /!gameFullscreen && !embedFailure/)
  assert.match(games, />Back to games<\/button>/)
  assert.match(games, />Reconnect<\/button>/)
  assert.match(games, />Screenshot<\/button>/)
  assert.match(games, />Resume game<\/button>/)
  assert.doesNotMatch(games, /group-hover\/game:opacity-100/)
  assert.match(embed, /let inputCaptureAllowed = true/)
  assert.match(embed, /inputCaptureAllowed = false/)
  assert.match(embed, /SYNNICAL_GAME_CAPTURE_INPUT"\) captureInput\(false, true\)/)
  assert.match(embed, /SYNNICAL_GAME_RELEASE_INPUT"\) releaseInput\(\)/)
})

test("r6 presence is account-persisted, privacy-first and emitted from the global app shell", () => {
  const presence = read("src/lib/presence.ts")
  const route = read("src/app/api/features/presence/route.ts")
  const bridge = read("src/components/presence-bridge.tsx")
  const shell = read("src/components/app-shell.tsx")
  assert.match(presence, /shareSection: false/)
  assert.match(presence, /showOnlineDuration: false/)
  assert.match(presence, /PRESENCE_SECTION_LABELS/)
  assert.match(route, /getPreference\(me\.id, KEY/)
  assert.match(route, /setPreference\(me\.id, KEY, next\)/)
  assert.match(bridge, /AFK_AFTER_MS = 5 \* 60 \* 1000/)
  assert.match(bridge, /synnical-panel-changed/)
  assert.match(bridge, /networkQuality: config\.shareNetworkQuality/)
  assert.match(bridge, /deviceType: config\.shareDevice/)
  assert.match(bridge, /new BroadcastChannel\(`synnical-presence:\$\{user\.id\}`\)/)
  assert.match(bridge, /channelRef\.current\?\.postMessage/)
  assert.match(shell, /<PresenceBridge \/>/)
  const settings = read("src/components/settings-extra-sections.tsx")
  assert.match(settings, /saveQueueRef/)
  assert.match(settings, /setDurationForCurrentMode/)
  assert.match(presence, /Busy until/)
})

test("r6 richer presence is user-level across sockets and visible in chat and profiles", () => {
  const server = read("src/lib/chat-server.ts")
  const chat = read("src/components/chat-panel.tsx")
  const profile = read("src/components/user-profile-modal.tsx")
  const settings = read("src/components/settings-extra-sections.tsx")
  assert.match(server, /const presenceByUser = new Map<string, PresenceState>\(\)/)
  assert.match(server, /socket\.on\("presence-update"/)
  assert.match(server, /presenceSection\(payload\.currentSection\)/)
  assert.match(server, /showOnlineDuration = payload\.showOnlineDuration === true/)
  assert.match(chat, /publicPresenceLabel\(u\.presenceMode, u\.afk, u\.presenceModeExpiresAt\)/)
  assert.match(chat, /presenceSectionLabel\(u\.currentSection\)/)
  assert.match(chat, /onlineDurationLabel\(u\.onlineSince\)/)
  assert.match(profile, /publicPresenceLabel\(presenceEntry\?\.presenceMode/)
  assert.match(profile, /presenceSectionLabel\(presenceEntry\?\.currentSection\)/)
  const friends = read("src/components/friends-panel.tsx")
  assert.match(friends, /socket\.on\("online-users", receive\)/)
  assert.match(friends, /Boolean\(onlinePresence\[u\.id\]\)/)
  assert.doesNotMatch(friends, /u\.status && u\.status !== "offline"/)
  assert.match(friends, /return aLabel\.localeCompare\(bLabel\)/)
  assert.match(settings, /Show People Rail/)
  assert.doesNotMatch(settings, /Display your online status to others/)
})

test("r6 accessibility controls all have runtime and CSS consumers", () => {
  const settings = read("src/components/settings-panel.tsx")
  const runtime = read("src/lib/settings-runtime.ts")
  const css = read("src/app/globals.css")
  for (const key of [
    "a11y.reduceMotion", "a11y.highContrast", "a11y.highLegibility", "a11y.dyslexiaFriendly",
    "a11y.interfaceDensity", "a11y.interfaceZoom", "a11y.lineSpacing", "a11y.messageSpacing",
    "a11y.focusThickness", "a11y.largePointer", "a11y.simplifiedUi",
  ]) {
    assert.match(settings, new RegExp(key.replaceAll(".", "\\.")))
    assert.match(runtime, new RegExp(key.replaceAll(".", "\\.")))
  }
  assert.match(runtime, /synnical-custom-line-spacing/)
  assert.match(css, /synnical-dyslexia-friendly/)
  assert.match(css, /synnical-setting-row/)
  assert.match(css, /--synnical-message-spacing/)
  assert.match(css, /--synnical-interface-zoom/)
  assert.match(css, /--synnical-focus-thickness/)
  assert.match(css, /\[data-synnical-cosmetic-preview\]/)
})

test("r6 performance controls include explicit and automatic low-end modes", () => {
  const settings = read("src/components/settings-extra-sections.tsx")
  const runtime = read("src/lib/settings-runtime.ts")
  const generic = read("src/components/settings-generic.tsx")
  assert.match(settings, /Low-End Device Mode/)
  assert.match(settings, /Automatic Performance Scaling/)
  assert.doesNotMatch(settings, /title="(?:DNS Prefetching|Max Connections|WebGL Renderer|Service Worker Cache|Canvas Acceleration|Data Saver)"/)
  assert.match(runtime, /adaptiveLowEndDetected/)
  assert.match(runtime, /hardwareConcurrency/)
  assert.match(runtime, /deviceMemory/)
  assert.match(runtime, /effectiveType/)
  assert.match(runtime, /readSetting\("perf\.autoScale", false\)/)
  assert.match(runtime, /synnical-perf-mode/)
  assert.match(generic, /connection\?\.addEventListener\?\.\("change"/)
})

test("r7.2 account directory keeps the redacted SafeUser list explicitly typed", () => {
  const route = read("src/app/api/chat/users/route.ts")
  assert.match(route, /import \{ toSafeUser, type SafeUser \} from ["']@\/lib\/auth["']/)
  assert.match(route, /const safe: SafeUser\[\] = \[\]/)
})

test("r7.1 custom-server shared policy modules do not use Next server-only sentinel", () => {
  const privacy = read("src/lib/privacy.ts")
  const security = read("src/lib/security-policy.ts")
  const chatServer = read("src/lib/chat-server.ts")
  assert.doesNotMatch(privacy, /import ["']server-only["']/)
  assert.doesNotMatch(security, /import ["']server-only["']/)
  assert.match(chatServer, /from ["']\.\/privacy["']/)
  assert.match(chatServer, /from ["']\.\/security-policy["']/)
})

test("r7 privacy rules are server-enforced and support per-friend view-as previews", () => {
  const schema = read("prisma/schema.prisma")
  const privacy = read("src/lib/privacy.ts")
  const route = read("src/app/api/features/privacy/route.ts")
  const profile = read("src/app/api/profile/[id]/route.ts")
  const featureProfile = read("src/app/api/features/profile/route.ts")
  const sockets = read("src/lib/chat-server.ts")
  const settings = read("src/components/r7-settings.tsx")
  assert.match(schema, /model PrivacyRule/)
  assert.match(schema, /@@unique\(\[userId, viewerId\]\)/)
  assert.match(privacy, /PRIVACY_PRESETS/)
  assert.match(privacy, /privacyViewFor/)
  assert.match(privacy, /close_friends/)
  assert.match(privacy, /private:\s*\{[\s\S]*profile: "nobody"/)
  assert.match(privacy, /privacyCache/)
  assert.match(route, /action === "set-rule"/)
  assert.match(route, /viewerId/)
  assert.match(profile, /privacy\.connections \? parseStoredConnections/)
  assert.match(profile, /privateProfile: !privacy\.profile/)
  assert.match(featureProfile, /privacy\.birthday/)
  assert.match(featureProfile, /privacy\.game \? target\.gameStatus/)
  assert.match(sockets, /usersForViewer/)
  assert.match(sockets, /if \(!privacy\.presence/)
  assert.match(sockets, /if \(!privacy\.activity\)/)
  assert.match(settings, /What can they see\?/)
  assert.match(settings, /Viewing your account as/)
})

test("r7 security has real sessions, recovery sign-in, protected actions and enforced lockdown", () => {
  const schema = read("prisma/schema.prisma")
  const auth = read("src/lib/auth-server.ts")
  const login = read("src/app/api/auth/login/route.ts")
  const security = read("src/app/api/features/security/route.ts")
  const policy = read("src/lib/security-policy.ts")
  const chat = read("src/lib/chat-server.ts")
  const shop = read("src/lib/shop-economy.ts")
  const ui = read("src/components/r7-settings.tsx")
  assert.match(schema, /deviceName\s+String\s+@default\(""\)/)
  assert.match(schema, /lastSeenAt\s+DateTime\s+@default\(now\(\)\)/)
  assert.match(schema, /model RecoveryCode/)
  assert.match(schema, /model SecurityEvent/)
  assert.match(auth, /createSession\(userId: string, req\?: NextRequest\)/)
  assert.match(auth, /getCurrentSession/)
  assert.match(login, /consumeRecoveryCode/)
  assert.match(login, /recoveryOk/)
  assert.match(security, /action === "generate-recovery-codes"/)
  assert.match(security, /action === "revoke-session"/)
  assert.match(security, /Content-Disposition/)
  assert.match(security, /sessions\.map\(\(\{ token: _token/)
  assert.match(policy, /LOCKDOWN_KEY/)
  assert.match(policy, /makeRecoveryCodes/)
  assert.match(chat, /ACCOUNT_LOCKDOWN/)
  assert.match(chat, /account lockdown blocks outgoing scheduled messages/)
  assert.match(shop, /Account lockdown is on/)
  assert.match(ui, /Emergency account lockdown/)
  assert.match(ui, /Security score \/ 100/)
  assert.match(ui, /Signed-in devices/)
  assert.match(ui, /export function R7DevicesControls/)
  const settingsPanel = read("src/components/settings-panel.tsx")
  assert.match(settingsPanel, /<R7DevicesControls \/>/)
  assert.doesNotMatch(settingsPanel, /Detailed session management is not available/)
})

test("r7 Synnical Lab has independent flags, selected testers, feedback and stable opt-out", () => {
  const schema = read("prisma/schema.prisma")
  const flags = read("src/lib/feature-flags.ts")
  const route = read("src/app/api/features/lab/route.ts")
  const panel = read("src/components/synnical-lab-panel.tsx")
  const shell = read("src/components/app-shell.tsx")
  assert.match(schema, /model FeatureFlag/)
  assert.match(schema, /rolloutPercent\s+Int\s+@default\(0\)/)
  assert.match(schema, /model LabEnrollment/)
  assert.match(schema, /model LabFeedback/)
  assert.match(flags, /createHash\("sha256"\)/)
  assert.match(flags, /bucket\(userId, key\)/)
  assert.match(flags, /enrollment\?\.optedOut/)
  assert.match(route, /action === "upsert-flag"/)
  assert.match(route, /action === "enroll-user"/)
  assert.match(route, /action === "remove-enrollment"/)
  assert.match(route, /action === "feedback"/)
  assert.match(route, /kind: \{ in: \["ship", "needs_work"\] \}/)
  assert.match(route, /action === "opt-out"/)
  assert.match(panel, /Return to stable/)
  assert.match(panel, /Disable instantly/)
  assert.match(panel, /Remove tester/)
  assert.match(shell, /labOnly: true/)
  assert.match(shell, /labVisible/)
})

test("r7 removes browser-only controls that falsely claimed to control account privacy", () => {
  const profileSettings = read("src/components/settings-extra-sections.tsx")
  const profilePanel = read("src/components/profile-panel.tsx")
  const modal = read("src/components/user-profile-modal.tsx")
  assert.match(profileSettings, /Profile Card Display/)
  assert.match(profileSettings, /controlled server-side in Privacy & Safety/)
  assert.doesNotMatch(profileSettings, /title="Allow Profile Views"/)
  assert.doesNotMatch(profileSettings, /title="Profile Visibility"/)
  assert.doesNotMatch(profilePanel, /profile\.visibility/)
  assert.match(profilePanel, /real visibility rules are enforced on the server/)
  assert.doesNotMatch(modal, /profile\.visibility/)
  assert.match(modal, /Synnical applies these privacy rules on the server/)
})

test("r8 staff audit logs are append-only snapshots wired at action sources", () => {
  const schema = read("prisma/schema.prisma")
  const helper = read("src/lib/audit-log.ts")
  const route = read("src/app/api/moderation/audit/route.ts")
  assert.match(schema, /model AuditLog/)
  assert.match(schema, /actorUsernameSnapshot/)
  assert.match(schema, /targetUsernameSnapshot/)
  assert.doesNotMatch(schema.match(/model AuditLog[\s\S]*?\n\}/)?.[0] || "", /@relation/)
  assert.match(helper, /auditData/)
  assert.match(helper, /recordAuditLog/)
  assert.match(route, /export async function GET/)
  assert.doesNotMatch(route, /export async function (?:POST|PATCH|DELETE)/)

  for (const file of [
    "src/app/api/moderation/credits/route.ts",
    "src/app/api/moderation/accounts/route.ts",
    "src/app/api/moderation/mute/route.ts",
    "src/app/api/moderation/unmute/route.ts",
    "src/app/api/infractions/create/route.ts",
    "src/app/api/infractions/delete/route.ts",
    "src/app/api/reports/route.ts",
    "src/app/api/roles/assign/route.ts",
    "src/app/api/moderation/media/route.ts",
    "src/app/api/messages/[id]/route.ts",
    "src/app/api/features/lab/route.ts",
    "src/app/api/channels/announcement/route.ts",
    "src/app/api/owner/verify/route.ts",
  ]) assert.match(read(file), /audit(?:Data|Log)/i, `${file} must write the central audit trail`)
})

test("r8 member directories use server-side search filters and pagination", () => {
  const route = read("src/app/api/roles/users/route.ts")
  const apiClient = read("src/lib/api.ts")
  const moderation = read("src/components/staff-accounts-panel.tsx")
  const settings = read("src/components/settings-panel.tsx")
  const actions = read("src/components/infractions-panel.tsx")
  assert.match(route, /searchParams\.get\("q"\)/)
  assert.match(route, /searchParams\.get\("page"\)/)
  assert.match(route, /searchParams\.get\("pageSize"\)/)
  assert.match(route, /db\.user\.count\(\{ where \}\)/)
  assert.match(route, /skip: \(page - 1\) \* pageSize/)
  assert.match(route, /take: pageSize/)
  assert.doesNotMatch(route, /take: 200/)
  assert.match(apiClient, /listUsers: \(params\?:/)
  assert.match(moderation, /Search members/)
  assert.match(moderation, /pageSize: "25"/)
  assert.match(moderation, /Audit Logs/)
  assert.match(moderation, /Reports & Actions/)
  assert.match(settings, /Search username, display name, ID or role/)
  assert.match(settings, /pageSize: 25/)
  assert.match(actions, /api\.listUsers\(\{ q: query\.trim\(\), page: 1, pageSize: 50 \}\)/)
})

test("r8 audit UI exposes actor target reason changes and scalable filtering", () => {
  const panel = read("src/components/audit-log-panel.tsx")
  assert.match(panel, /Staff Audit Logs/)
  assert.match(panel, /Append-only history of staff actions/)
  assert.match(panel, /actorUsernameSnapshot/)
  assert.match(panel, /targetUsernameSnapshot/)
  assert.match(panel, /Reason:/)
  assert.match(panel, /ValueChanges/)
  assert.match(panel, /category/)
  assert.match(panel, /action/)
  assert.match(panel, /pageSize: "30"/)
  assert.match(panel, /Previous/)
  assert.match(panel, /Next/)
})

test("r9 friendship social layer persists duo XP, memories, goals and milestones without duplicating private friend metadata", () => {
  const schema = read("prisma/schema.prisma")
  assert.match(schema, /model FriendshipBond/)
  assert.match(schema, /pairKey\s+String\s+@unique/)
  assert.match(schema, /messageCount\s+Int\s+@default\(0\)/)
  assert.match(schema, /model FriendshipMemory/)
  assert.match(schema, /model FriendshipGoal/)
  assert.match(schema, /model FriendshipMilestone/)
  assert.match(schema, /label\s+String\s+@default\(""\)/)
  assert.doesNotMatch(schema.match(/model FriendshipBond[\s\S]*?\n\}/)?.[0] || "", /@relation/)
})

test("r9 friendship XP is wired to real friend DMs and rate-limited against spam", () => {
  const engine = read("src/lib/friendship-social.ts")
  const chat = read("src/lib/chat-server.ts")
  assert.match(engine, /acceptedFriendship/)
  assert.match(engine, /recordFriendshipMessage/)
  assert.match(engine, /60_000/)
  assert.match(engine, /xpGain/)
  assert.match(chat, /recordFriendshipMessage/)
  assert.match(chat, /if \(dmPeerId\)/)
  assert.match(chat, /if \(channel\.isDM\)/)
  assert.match(chat, /scheduled message/)
})

test("r9 friendship API is pair-authorized and keeps destructive scrapbook actions creator-owned", () => {
  const route = read("src/app/api/features/friends/route.ts")
  assert.match(route, /acceptedPair\(me\.id, friendId\)/)
  assert.match(route, /ensureFriendshipBond\(me\.id, friendId\)/)
  assert.match(route, /creatorId: me\.id/)
  assert.match(route, /deleteMany\(\{ where: \{ id, pairKey, creatorId: me\.id \} \}\)/)
  assert.match(route, /That duo title is not unlocked yet/)
  assert.match(route, /Friendship scrapbook limit reached/)
})

test("r9 duo UI exposes levels milestones scrapbook goals reconnect and honest taste matching", () => {
  const ui = read("src/components/friendship-social-dialog.tsx")
  const friends = read("src/components/friends-panel.tsx")
  assert.match(ui, /Duo level/)
  assert.match(ui, /friendship XP/)
  assert.match(ui, /Milestones/)
  assert.match(ui, /friendship scrapbook/)
  assert.match(ui, /Create a shared goal/)
  assert.match(ui, /You haven't talked in/)
  assert.match(ui, /do not pretend to know which PC games you own/)
  assert.match(ui, /data\.source/)
  const route = read("src/app/api/features/friends/route.ts")
  assert.match(route, /Synnical game favourites/)
  assert.match(route, /SynnFlix watchlists and favourites/)
  assert.match(route, /Artists in saved Synnical playlists/)
  assert.match(friends, /Open friendship duo card/)
  assert.match(friends, /Friendship label/)
  assert.match(friends, /Duo Lv/)
})

test("r9 account deletion cleans friendship social data while audit snapshots remain independent", () => {
  const route = read("src/app/api/moderation/accounts/route.ts")
  assert.match(route, /tx\.friendshipBond\.findMany/)
  assert.match(route, /tx\.friendshipMemory\.deleteMany/)
  assert.match(route, /tx\.friendshipGoal\.deleteMany/)
  assert.match(route, /tx\.friendshipMilestone\.deleteMany/)
  assert.match(route, /tx\.friendshipBond\.deleteMany/)
  assert.match(route, /tx\.friendMeta\.deleteMany/)
  assert.match(route, /tx\.auditLog\.create/)
})

test("r9 existing friends bootstrap from durable DM history instead of starting every duo at zero", () => {
  const engine = read("src/lib/friendship-social.ts")
  assert.match(engine, /historicDmStats/)
  assert.match(engine, /db\.message\.count/)
  assert.match(engine, /lastInteractionAt/)
  assert.match(engine, /bootstrapXp = Math\.min\(historic\.messageCount, 400\)/)
  assert.match(engine, /db\.friendshipBond\.upsert/)
  const chat = read("src/lib/chat-server.ts")
  assert.match(chat, /ensureFriendshipBond\(user\.userId, dmPeerId\)[\s\S]{0,180}const created = await db\.message\.create/)
})

test("r9.1 game compatibility accepts database string IDs without literal-key TypeScript narrowing", () => {
  const route = read("src/app/api/features/friends/route.ts")
  assert.match(route, /new Map<string, string>\(CLOUD_GAMES\.map/)
  assert.match(route, /gameNames\.get\(id\)/)
})


test("r10 SynnFlix keeps a stable fullscreen shell across episode/player changes", () => {
  const ui = read("src/components/synnflix-panel.tsx")
  assert.match(ui, /fullscreenShellRef = useRef<HTMLElement/)
  assert.match(ui, /shell\.requestFullscreen/)
  assert.match(ui, /document\.fullscreenElement === fullscreenShellRef\.current/)
  assert.match(ui, /<section ref=\{fullscreenShellRef\}/)
  assert.match(ui, /synnical:synnflix:last-context/)
  assert.doesNotMatch(ui, /key=\{[^\n}]*currentTime/)
})

test("r10 social spaces use authenticated membership and server-owned voting identity", () => {
  const schema = read("prisma/schema.prisma")
  const route = read("src/app/api/features/spaces/route.ts")
  const ui = read("src/components/spaces-panel.tsx")
  assert.match(schema, /model SocialSpace/)
  assert.match(schema, /model SocialSpaceMember/)
  assert.match(schema, /model SocialSpaceItem/)
  assert.match(route, /canReadSpace\(spaceId, me\.id\)/)
  assert.match(route, /action === "toggle-vote"/)
  assert.match(route, /value !== me\.id/)
  assert.match(route, /option\.voters\.includes\(me\.id\)/)
  assert.match(route, /"mood"/)
  assert.match(ui, /Shared clipboard|Whiteboard|Jukebox|Trivia/)
})

test("r10 market transactions reserve mutable rows and reject unsafe empty or duplicate trades", () => {
  const schema = read("prisma/schema.prisma")
  const route = read("src/app/api/features/market/route.ts")
  const ui = read("src/components/market-panel.tsx")
  assert.match(schema, /model MarketplaceListing/)
  assert.match(schema, /model TradeOffer/)
  assert.match(schema, /model CosmeticOwnershipEvent/)
  assert.match(route, /status:"processing"/)
  assert.match(route, /Trades are limited to accepted friends/)
  assert.match(route, /A trade must include credits or at least one cosmetic/)
  assert.match(route, /Requested cosmetics must be unique/)
  assert.match(route, /trade safety cooldown/)
  assert.match(route, /pot-cancel/)
  assert.match(route, /shared_pot_refund/)
  assert.match(ui, /Load friend/)
  assert.match(ui, /Request from friend/)
  assert.match(ui, /Cancel & refund/)
})

test("r10 automations have server triggers, a kill switch, browser action queue and undo", () => {
  const schema = read("prisma/schema.prisma")
  const engine = read("src/lib/automation-engine.ts")
  const route = read("src/app/api/features/automations/route.ts")
  const bridge = read("src/components/automation-bridge.tsx")
  assert.match(schema, /model AutomationRule/)
  assert.match(schema, /model AutomationRun/)
  assert.match(engine, /automation\.killSwitch/)
  assert.match(engine, /status: "pending_client"/)
  assert.match(engine, /runAutomationTrigger/)
  assert.match(engine, /undoAutomationRun/)
  assert.match(route, /action === "preview"/)
  assert.match(route, /action === "share-template"/)
  assert.match(route, /action === "import-template"/)
  assert.match(bridge, /synnical-open-panel/)
  assert.match(bridge, /synnical-music-mute/)
})

test("r10 personas are selected on the server and public profiles consume the selected persona", () => {
  const schema = read("prisma/schema.prisma")
  const identity = read("src/lib/identity-profile.ts")
  const route = read("src/app/api/profile/[id]/route.ts")
  assert.match(schema, /model Persona/)
  assert.match(identity, /visiblePersonaFor/)
  assert.match(identity, /closeFriend/)
  assert.match(route, /visiblePersonaFor\(target\.id, viewer\.id\)/)
  assert.match(route, /displayName: persona\.displayName/)
})

test("r10 episode spoiler tags persist real media metadata and hide tagged content until reveal", () => {
  const schema = read("prisma/schema.prisma")
  const server = read("src/lib/chat-server.ts")
  const ui = read("src/components/chat-panel.tsx")
  assert.match(schema, /spoilerMediaType\s+String\?/)
  assert.match(schema, /spoilerSeason\s+Int\?/)
  assert.match(schema, /spoilerUntil\s+DateTime\?/)
  assert.match(server, /spoilerMediaType: spoilerMeta\?\.mediaType/)
  assert.match(server, /spoilerUntil: spoilerMeta\?\.until/)
  assert.match(ui, /EpisodeSpoilerReveal/)
  assert.match(ui, /Click to reveal/)
})

test("r10 browser workspaces persist account layouts and split-screen is a real two-tab layout", () => {
  const schema = read("prisma/schema.prisma")
  const route = read("src/app/api/features/browser/route.ts")
  const ui = read("src/components/browser-panel.tsx")
  assert.match(schema, /model BrowserWorkspace/)
  assert.match(route, /action === "save-workspace"/)
  assert.match(route, /userId_name/)
  assert.match(route, /action === "delete-workspace"/)
  assert.match(ui, /splitTabId/)
  assert.match(ui, /Split-screen website/)
  assert.match(ui, /School/)
  assert.match(ui, /Gaming/)
})

test("r10 Creator Studio keeps collaborators friend-authorized and project deletion owner-only", () => {
  const schema = read("prisma/schema.prisma")
  const route = read("src/app/api/features/creator/route.ts")
  assert.match(schema, /model CreatorProject/)
  assert.match(schema, /model CreatorProjectVersion/)
  assert.match(route, /Collaborator must be an accepted friend/)
  assert.match(route, /Only the owner can manage collaborators/)
  assert.match(route, /Only the owner can delete this project/)
  assert.match(route, /More than 30 keyframes may be expensive/)
})

test("r10 calls use authenticated same-room signalling and genuinely stop screen capture", () => {
  const server = read("src/lib/chat-server.ts")
  const ui = read("src/components/calls-panel.tsx")
  assert.match(server, /callRooms = new Map/)
  assert.match(server, /room\.members\.size >= 6/)
  assert.match(server, /callRoomBySocket\.get\(target\) !== code/)
  assert.match(server, /room\?\.members\.has\(socket\.id\)/)
  assert.match(ui, /getUserMedia/)
  assert.match(ui, /getDisplayMedia/)
  assert.match(ui, /screenTrackRef\.current = null/)
  assert.match(ui, /sharing\.stop\(\)/)
  assert.match(ui, /NEXT_PUBLIC_WEBRTC_ICE_SERVERS_JSON/)
})

test("r10 security has password-confirmed temporary and permanent trusted devices", () => {
  const schema = read("prisma/schema.prisma")
  const route = read("src/app/api/features/security/route.ts")
  const ui = read("src/components/r7-settings.tsx")
  assert.match(schema, /trustedAt\s+DateTime\?/)
  assert.match(schema, /trustedUntil\s+DateTime\?/)
  assert.match(route, /"trust-session"/)
  assert.match(route, /"untrust-session"/)
  assert.match(route, /verifyPassword/)
  assert.match(route, /session_trusted/)
  assert.match(ui, /Trust 7 days|Trust/)
  assert.match(ui, /Untrust/)
})

test("r10 developer tokens are hashed, scoped, read-only and shown only at creation", () => {
  const schema = read("prisma/schema.prisma")
  const auth = read("src/lib/developer-auth.ts")
  const route = read("src/app/api/features/developer/route.ts")
  const me = read("src/app/api/developer/v1/me/route.ts")
  const panel = read("src/components/developer-panel.tsx")
  assert.match(schema, /model DeveloperToken/)
  assert.match(auth, /createHash\("sha256"\)/)
  assert.match(auth, /DEVELOPER_SCOPES/)
  assert.match(route, /verifyPassword/)
  assert.match(route, /newToken: rawToken/)
  assert.match(route, /tokenHash: developerTokenHash\(rawToken\)/)
  assert.match(me, /read:profile/)
  assert.doesNotMatch(me, /export async function POST/)
  assert.match(panel, /will not show it again/)
})

test("r10 command palette shares the app launcher path needed by future OS mode", () => {
  const registry = read("src/lib/app-registry.ts")
  const palette = read("src/components/command-palette.tsx")
  const shell = read("src/components/app-shell.tsx")
  assert.match(registry, /SYNNICAL_APPS/)
  assert.match(registry, /id: "developer"[^\n]+authOnly: true/)
  assert.match(palette, /event\.ctrlKey \|\| event\.metaKey/)
  assert.match(palette, /synnical-open-panel/)
  assert.match(palette, /app\.authOnly/)
  assert.match(shell, /<CommandPalette \/>/)
  assert.match(shell, /targetNav\.authOnly && !user/)
  assert.match(shell, /targetNav\.labOnly && !labVisible/)
})

test("r10 account deletion cleans mega-expansion data and refunds other users from active shared pots", () => {
  const route = read("src/app/api/moderation/accounts/route.ts")
  for (const needle of [
    /tx\.socialSpace\.deleteMany/,
    /tx\.automationRule\.deleteMany/,
    /tx\.creatorProject\.deleteMany/,
    /tx\.featureRecord\.deleteMany/,
    /tx\.persona\.deleteMany/,
    /tx\.mediaProgress\.deleteMany/,
    /tx\.browserWorkspace\.deleteMany/,
    /tx\.developerToken\.deleteMany/,
    /tx\.creditVault\.deleteMany/,
  ]) assert.match(route, needle)
  assert.match(route, /shared_pot_refund/)
  assert.match(route, /cancelled_account_deleted/)
  assert.match(route, /cosmeticOwnershipEvent\.updateMany/)
})

test("r10 intentionally contains no virtual-machine data model or fake VM feature surface", () => {
  const schema = read("prisma/schema.prisma")
  const shell = read("src/components/app-shell.tsx")
  assert.doesNotMatch(schema, /model\s+(?:VM|Vm|VirtualMachine)\b/)
  assert.doesNotMatch(shell, /id:\s*"(?:vm|virtual-machine|cloud-computer)"/i)
})

test("r10.1 preflight type boundaries match the real Prisma schema and client runtime shapes", () => {
  const devFriends = read("src/app/api/developer/v1/friends/route.ts")
  const automationRoute = read("src/app/api/features/automations/route.ts")
  const automationEngine = read("src/lib/automation-engine.ts")
  const gamesRoute = read("src/app/api/features/games/route.ts")
  const identityRoute = read("src/app/api/features/identity/route.ts")
  const identityProfile = read("src/lib/identity-profile.ts")
  const chatServer = read("src/lib/chat-server.ts")
  const marketRoute = read("src/app/api/features/market/route.ts")
  const musicSocial = read("src/app/api/features/music-social/route.ts")
  const securityRoute = read("src/app/api/features/security/route.ts")
  const automationBridge = read("src/components/automation-bridge.tsx")
  const browser = read("src/components/browser-panel.tsx")

  assert.match(devFriends, /db\.friendship\.findMany/)
  assert.doesNotMatch(devFriends, /db\.friendRequest/)
  for (const source of [devFriends, automationRoute, gamesRoute, identityRoute, identityProfile, chatServer]) {
    assert.doesNotMatch(source, /friendship[^\n]*senderId|senderId[^\n]*friendship/)
  }
  assert.match(devFriends, /requesterId/)
  assert.match(automationRoute, /requesterId: me\.id/)
  assert.match(gamesRoute, /requesterId: me\.id/)
  assert.match(identityRoute, /requesterId: a/)
  assert.match(identityProfile, /requesterId: targetId/)
  assert.match(chatServer, /select: \{ requesterId: true, receiverId: true \}/)

  assert.match(automationEngine, /const runs: Array<\{ id: string \}> = \[\]/)
  assert.match(marketRoute, /const rawSenderIds: string\[\]/)
  assert.match(marketRoute, /new Set<string>\(rawSenderIds\)/)
  assert.match(musicSocial, /db\.musicPlaylistTrack\.findMany/)
  assert.doesNotMatch(musicSocial, /musicPlaylist\.findMany\([^\n]*include:\s*\{\s*tracks/)
  assert.match(securityRoute, /row: \{ trustedAt: Date \| null; trustedUntil: Date \| null \}/)
  assert.match(automationBridge, /undo\?: Record<string, unknown>/)
  assert.match(browser, /layout: splitTabId && splitTabId !== activeId \? "split" : "tabs"/)
})

test("r11.3 removes the Tools container and promotes permitted apps to the desktop", () => {
  const shell = read("src/components/app-shell.tsx")
  const desktop = read("src/components/desktop-shell.tsx")
  const registry = read("src/lib/app-registry.ts")
  assert.doesNotMatch(shell, /id: "tools"|panel: "tools"|<ToolsPanel/)
  assert.doesNotMatch(registry, /id: "tools"/)
  assert.match(shell, /id: "creator"[\s\S]{0,180}authOnly: true/)
  assert.match(shell, /id: "temp-mail"/)
  assert.match(shell, /id: "youtube", label: "YouTube"/)
  assert.match(shell, /id: "geforce-now", label: "GeForce NOW"/)
  assert.match(desktop, /\{desktopApps\.map\(\(app, index\) =>/)
  assert.match(desktop, /Recycle Bin/)
})


test("r11 Synnical OS uses real panel windows with persistent layout, snapping, workspaces and taskbar", () => {
  const desktop = read("src/components/desktop-shell.tsx")
  const shell = read("src/components/app-shell.tsx")
  assert.match(shell, /<DesktopShell/)
  assert.match(shell, /renderPanel=\{renderDesktopPanel\}/)
  assert.match(desktop, /WINDOW_KEY = "synnical:os:windows:v2"/)
  assert.match(desktop, /persistWindows/)
  assert.match(desktop, /current\.find\(\(win\) => win\.panel === panel\)/)
  assert.match(desktop, /workspace, minimized: false/)
  assert.match(desktop, /snapWindowRect/)
  assert.match(desktop, /snapZone/)
  assert.match(desktop, /"left" \| "right" \| "max" \| "tl" \| "tr" \| "bl" \| "br" \| "wide" \| "narrow"/)
  assert.match(desktop, /event\.altKey && event\.key === "Tab"/)
  assert.match(desktop, /os\.workspaces\.map\(\(desktop\) =>/)
  assert.match(desktop, /Task View/)
  assert.match(desktop, /Quick Settings/)
  assert.match(desktop, /Show desktop/)
  assert.match(desktop, /renderPanel\(win\.panel, openPanel\)/)
  assert.match(desktop, /synnical-taskbar/)
  assert.match(desktop, /system\.batterySupported/)
  assert.match(desktop, /system\.online/)
})

test("r11 desktop lock screen verifies the current account password server-side", () => {
  const desktop = read("src/components/desktop-shell.tsx")
  const security = read("src/app/api/features/security/route.ts")
  assert.match(desktop, /action: "verify-password"/)
  assert.match(desktop, /Click or press a key to sign in/)
  assert.match(desktop, /placeholder="Password"/)
  assert.match(desktop, /setLocked\(false\)/)
  assert.match(security, /"verify-password"/)
  assert.match(security, /verifyPassword\(password, current\.user\.passwordHash\)/)
  assert.match(security, /action === "verify-password"\) return NextResponse\.json\(\{ verified: true \}\)/)
})

test("r11 OS notification center consumes real app events instead of fake notification rows", () => {
  const desktop = read("src/components/desktop-shell.tsx")
  const automation = read("src/components/automation-bridge.tsx")
  assert.match(desktop, /synnical-os-notify/)
  assert.match(desktop, /synnical-chat-unread/)
  assert.match(desktop, /No new notifications/)
  assert.match(desktop, /Clear all/)
  assert.match(desktop, /calendarCells/)
  assert.match(automation, /synnical-os-notify/)
})


test("r11.1 makes Synnical OS the real default and syncs OS preferences to the account", () => {
  const shell = read("src/components/app-shell.tsx")
  const settings = read("src/lib/os-settings.ts")
  const route = read("src/app/api/features/os/route.ts")
  assert.match(shell, /readSetting\("layout\.osMode", true\)/)
  assert.match(shell, /hydrateOsSettings\(\)/)
  assert.match(settings, /enabled: true/)
  assert.match(settings, /taskbarAlignment: "center"/)
  assert.match(settings, /taskbarAutoHide/)
  assert.match(settings, /snapLayouts/)
  assert.match(route, /getPreference<[\s\S]{1,80}>\(me\.id, "os\.settings"/)
  assert.match(route, /setPreference\(me\.id, "os\.settings", settings\)/)
})

test("r11.1 Synnical Settings is a Windows-grade category shell without Microsoft branding", () => {
  const app = read("src/components/synnical-settings-app.tsx")
  const shell = read("src/components/app-shell.tsx")
  for (const label of ["System", "Bluetooth & devices", "Network & internet", "Personalization", "Apps", "Accounts", "Time & language", "Gaming", "Accessibility", "Privacy & security", "Synnical Update"]) assert.match(app, new RegExp(label.replace(/[&]/g, "\\&")))
  assert.match(app, /Find a setting/)
  assert.match(app, /Taskbar/)
  assert.match(app, /Snap windows/)
  assert.match(app, /Visual effects/)
  assert.match(app, /Synnical does not invent a remote update result/)
  assert.match(app, /synnical-settings-category/)
  assert.match(shell, /<SynnicalSettingsApp \/>/)
  assert.doesNotMatch(app, /Microsoft|Windows Update|Windows logo/)
})

test("r11.1 Synnical Files is a real account-backed explorer surface, not a fake local drive", () => {
  const files = read("src/components/synnical-files-panel.tsx")
  const shell = read("src/components/app-shell.tsx")
  const registry = read("src/lib/app-registry.ts")
  assert.match(shell, /id: "files", label: "Synnical Files"/)
  assert.match(shell, /<SynnicalFilesPanel \/>/)
  assert.match(registry, /id: "files"/)
  assert.match(files, /\/api\/features\/browser/)
  assert.match(files, /\/api\/features\/games/)
  assert.match(files, /\/api\/features\/games\/screenshot\/\$\{encodeURIComponent\(item\.rawId\)\}/)
  assert.match(files, /Home/)
  assert.match(files, /Downloads/)
  assert.match(files, /Screenshots/)
  assert.match(files, /Recycle Bin/)
  assert.match(files, /Ctrl\+T/)
  assert.match(files, /Move to Recycle Bin/)
  assert.match(files, /patchScreenshot\(menu\.item, "restore"\)/)
  assert.match(files, /patchScreenshot\(item, "purge"\)/)
  assert.match(files, /Cut requires a movable Synnical folder destination/)
  assert.match(files, /Paste requires a writable Synnical folder destination/)
})

test("r11.1 taskbar, Start, Quick Settings and utilities use real Synnical state", () => {
  const desktop = read("src/components/desktop-shell.tsx")
  const status = read("src/hooks/use-system-status.ts")
  assert.match(desktop, /aria-label="Start"/)
  assert.match(desktop, /All apps/)
  assert.match(desktop, /Recommended/)
  assert.match(desktop, /Pinned/)
  assert.match(desktop, /Running app|runningPanels|running=Boolean/)
  assert.match(desktop, /Quick Settings/)
  assert.match(desktop, /Bluetooth/)
  assert.match(desktop, /Airplane mode/)
  assert.match(desktop, /Battery saver/)
  assert.match(desktop, /Clipboard history/)
  assert.match(desktop, /Emoji · GIFs · symbols/)
  assert.match(desktop, /Touch keyboard/)
  assert.match(status, /navigator\.onLine/)
  assert.match(status, /getBattery/)
  assert.match(status, /effectiveType/)
  assert.doesNotMatch(desktop, /fake battery|fake wifi/i)
})

test("r11.2 OS account surfaces use the real SafeUser pfpUrl contract instead of nonexistent avatar", () => {
  const api = read("src/lib/api.ts")
  const auth = read("src/lib/auth.ts")
  const desktop = read("src/components/desktop-shell.tsx")
  const settings = read("src/components/synnical-settings-app.tsx")
  assert.match(api, /export type SafeUser = \{[\s\S]*pfpUrl: string \| null/)
  assert.match(auth, /export type SafeUser = \{[\s\S]*pfpUrl: string \| null/)
  assert.match(desktop, /user\?\.pfpUrl \? <img src=\{user\.pfpUrl\}/)
  assert.match(settings, /user\?\.pfpUrl \? <img src=\{user\.pfpUrl\}/)
  assert.doesNotMatch(desktop, /user\?\.avatar|user\.avatar/)
  assert.doesNotMatch(settings, /user\?\.avatar|user\.avatar/)
})


test("r11.3 wallpaper personalization is account-backed for desktop and lock screen", () => {
  const os = read("src/lib/os-settings.ts")
  const route = read("src/app/api/features/os/wallpaper/route.ts")
  const settings = read("src/components/synnical-settings-app.tsx")
  const desktop = read("src/components/desktop-shell.tsx")
  assert.match(os, /DEFAULT_OS_WALLPAPER = "\/brand\/wallpapers\/sakura-samurai-2\.png"/)
  assert.match(os, /desktopWallpaperFit/)
  assert.match(os, /lockUseDesktopWallpaper/)
  assert.match(os, /lockWallpaperFit/)
  assert.match(route, /sharp\(input/)
  assert.match(route, /resize\(\{ width: 3840, height: 2160/)
  assert.match(route, /setPreference\(user\.id, "os\.settings", next\)/)
  assert.match(settings, /Browse photo or MP4/)
  assert.match(settings, /Browse lock-screen photo/)
  assert.match(settings, /Show notifications/)
  assert.match(desktop, /desktopWallpaperUrl/)
  assert.match(desktop, /os\.lockShowNotifications && notices\.length/)
})

test("r12 removes the obsolete mandatory password migration while preserving secure recovery", () => {
  const schema = read("prisma/schema.prisma")
  const auth = read("src/lib/auth.ts")
  const server = read("src/lib/auth-server.ts")
  const security = read("src/app/api/features/security/route.ts")
  const recovery = read("src/app/api/auth/forgot-password/route.ts")
  const shell = read("src/components/app-shell.tsx")
  assert.match(schema, /securityQuestion\s+String\?/)
  assert.match(schema, /securityAnswerHash\s+String\?/)
  assert.match(auth, /securitySetupRequired: false/)
  assert.match(server, /hashSecurityAnswer/)
  assert.match(server, /verifySecurityAnswer/)
  assert.match(security, /mandatory one-time password migration has been removed/i)
  assert.match(security, /action === "change-password"/)
  assert.match(recovery, /verifySecurityAnswer\(securityAnswer, user\.securityAnswerHash\)/)
  assert.match(recovery, /recoveryCodeHash\(recoveryCode\)/)
  assert.doesNotMatch(shell, /SecuritySetupScreen/)
  assert.equal(existsSync(new URL("../src/components/security-setup-screen.tsx", import.meta.url)), false)
  assert.doesNotMatch(schema, /securityAnswer\s+String(?!Hash)/)
})

test("r11.3 real online presence cannot be hidden by privacy settings", () => {
  const privacy = read("src/lib/privacy.ts")
  const ui = read("src/components/r7-settings.tsx")
  assert.match(privacy, /presence: "everyone"/)
  assert.match(privacy, /out\.presence = "everyone"/)
  assert.match(privacy, /data\.sharePresence = true/)
  assert.match(ui, /real online\/offline state is always shown/)
  assert.doesNotMatch(ui, /Online presence/)
})

test("r11.3 touch keyboard types into the last focused editable Synnical field", () => {
  const desktop = read("src/components/desktop-shell.tsx")
  assert.match(desktop, /editableRef = useRef<EditableTarget \| null>/)
  assert.match(desktop, /document\.addEventListener\("focusin"/)
  assert.match(desktop, /editableRef\.current = target/)
  assert.match(desktop, /onPointerDown=\{\(e\)=>e\.preventDefault\(\)\}/)
  assert.match(desktop, /typeVirtual\(" "\)/)
  assert.match(desktop, /virtualBackspace/)
  assert.match(desktop, /virtualEnter/)
  assert.match(desktop, /Browser security prevents synthetic typing into cross-origin embedded pages/)
})

test("r11.3 YouTube and GeForce NOW are first-class branded OS apps", () => {
  const shell = read("src/components/app-shell.tsx")
  const registry = read("src/lib/app-registry.ts")
  const brands = read("src/components/brand-app-icons.tsx")
  const youtube = read("src/components/youtube-panel.tsx")
  const gfn = read("src/components/geforce-now-panel.tsx")
  assert.match(shell, /id: "youtube", label: "YouTube", icon: YouTubeIcon/)
  assert.match(shell, /id: "geforce-now", label: "GeForce NOW", icon: GeForceNowIcon/)
  assert.doesNotMatch(shell, /id: "extensions"/)
  assert.doesNotMatch(registry, /id: "extensions"/)
  assert.match(registry, /id: "youtube"/)
  assert.match(registry, /id: "geforce-now"/)
  assert.match(brands, /cdn\.simpleicons\.org\/youtube/)
  assert.match(brands, /play\.geforcenow\.com\/favicon\.ico/)
  assert.match(youtube, /youtube-nocookie\.com\/embed/)
  assert.match(youtube, /allowFullScreen/)
  assert.match(gfn, /initialUrl="https:\/\/play\.geforcenow\.com\/"/)
  assert.match(gfn, /embeddedLabel="GeForce NOW"/)
})

test("r11.6 cloud account verification polls one sent code and respects provider cooldown", () => {
  const cloud = read("stratus/api.js")
  assert.match(cloud, /async function sendProviderVerification/)
  assert.match(cloud, /providerVerificationCooldownUntil/)
  assert.match(cloud, /65_000/)
  assert.match(cloud, /getVerificationCode\(mailJwt, 32\)/)
  assert.match(cloud, /not spammed with a second code/)
  assert.doesNotMatch(cloud, /resending to the same mailbox once|retrying once with a fresh mailbox/)
})

test("r11.3 login goes directly to OS mode without a hidden five-W activation gate", () => {
  const shell = read("src/components/app-shell.tsx")
  const source = [
    shell,
    read("src/components/desktop-shell.tsx"),
    read("src/app/page.tsx"),
  ].join("\n")
  assert.match(shell, /readSetting\("layout\.osMode", true\)/)
  assert.match(shell, /\{osMode \? \(/)
  assert.doesNotMatch(source, /KeyW|keyCode\s*===\s*87|five times|5 times|press W/i)
  assert.doesNotMatch(source, /event\.key\.toLowerCase\(\)\s*!==\s*["']w["']/i)
  assert.doesNotMatch(source, /presses\s*\+=\s*1|presses\s*>=\s*5/i)
  assert.doesNotMatch(source, /EducationCover/)
  assert.equal(existsSync(new URL("../src/components/education-cover.tsx", import.meta.url)), false)
  assert.match(read("src/app/page.tsx"), /return <AppShell \/>/)
})

test("r11.3 Personalization, password change and lock recovery are wired end to end", () => {
  const settings = read("src/components/synnical-settings-app.tsx")
  const desktop = read("src/components/desktop-shell.tsx")
  const security = read("src/app/api/features/security/route.ts")
  const recovery = read("src/app/api/auth/forgot-password/route.ts")
  assert.equal(existsSync(new URL("../public/brand/wallpapers/sakura-samurai-2.png", import.meta.url)), true)
  assert.match(settings, /THEMES\.map/)
  assert.match(settings, /Browse photo or MP4/)
  assert.match(settings, /Browse lock-screen photo/)
  assert.match(settings, /Lock now/)
  assert.match(settings, /action: "change-password"/)
  assert.match(security, /action === "change-password"/)
  assert.match(desktop, /Forgot my password/)
  assert.match(desktop, /fetch\("\/api\/auth\/forgot-password"/)
  assert.match(desktop, /securityAnswer: forgotAnswer/)
  assert.match(desktop, /recoveryCode: forgotCode/)
  assert.match(recovery, /verifySecurityAnswer\(securityAnswer, user\.securityAnswerHash\)/)
  assert.match(recovery, /usedAt: null/)
  assert.match(recovery, /usedAt: new Date\(\)/)
})


test("r11.4 recognition badges are visible beside roles but never grant permissions", () => {
  const tags = read("src/lib/recognition-tags.ts")
  const roleUi = read("src/components/role-ui.tsx")
  const roles = read("src/app/api/roles/assign/route.ts")
  const chat = read("src/components/chat-panel.tsx")
  const server = read("src/lib/chat-server.ts")
  assert.match(tags, /NOTABLE_PERSON_TAG = "Notable Person"/)
  assert.match(tags, /BIG_SITE_OWNER_TAG = "Big Site Owner"/)
  assert.match(roleUi, /recognitionTags\(tags\)/)
  assert.match(roleUi, /BIG SITE OWNER/)
  assert.match(roleUi, /NOTABLE PERSON/)
  assert.match(roles, /recognitionTag && !isOwnerLevel\(me\.role\)/)
  assert.match(roles, /Only the owner or Head Admin can manage recognition badges/)
  assert.match(roles, /five ordinary tags plus protected recognition badges/)
  assert.match(chat, /<RoleBadge role=\{role\} tags=\{m\.tags\}/)
  assert.match(server, /tags: \(\(\) => \{ try \{ return JSON\.parse\(row\.user\?\.tags \|\| "\[\]"\)/)
  assert.doesNotMatch(tags, /canManage|permission|role\s*=/i)
})


test("r11.4 uses wallpaper 2 by default and exposes all four original wallpapers", () => {
  const os = read("src/lib/os-settings.ts")
  const settings = read("src/components/synnical-settings-app.tsx")
  assert.match(os, /DEFAULT_OS_WALLPAPER = "\/brand\/wallpapers\/sakura-samurai-2\.png"/)
  for (let index = 1; index <= 4; index += 1) {
    const path = `../public/brand/wallpapers/sakura-samurai-${index}.png`
    assert.equal(existsSync(new URL(path, import.meta.url)), true)
    assert.match(os, new RegExp(`sakura-samurai-${index}\\.png`))
  }
  assert.match(settings, /BUILTIN_OS_WALLPAPERS\.map/)
  assert.match(settings, /Wallpaper 2 is the Synnical default/)
  assert.match(settings, /Lock-screen wallpapers/)
  assert.equal(existsSync(new URL("../public/brand/wallpapers/samurai-cherry-blossom.png", import.meta.url)), false)
})

test("r11.4 chat quote, inline polls and hot-row callbacks are wired for real chat use", () => {
  const chat = read("src/components/chat-panel.tsx")
  const route = read("src/app/api/features/chat/route.ts")
  const server = read("src/lib/chat-server.ts")
  assert.match(chat, /const quoted = `> \$\{authorName\}: \$\{body\}\\n\\n`/)
  assert.match(chat, /Quote added to your message/)
  assert.match(chat, /title="Quote in message"/)
  assert.match(chat, /socket\.emit\("publish-poll-message", \{ messageId \}\)/)
  assert.match(chat, /function InlinePoll/)
  assert.match(chat, /action: "poll-message"/)
  assert.match(route, /action === "poll-message"/)
  assert.match(server, /socket\.on\("publish-poll-message"/)
  assert.match(chat, /onFeatureTools=\{openMessageTools\}/)
  assert.match(chat, /onToggleSaved=\{toggleSavedMessage\}/)
  assert.match(chat, /contentVisibility: "auto"/)
  assert.match(chat, /window\.setTimeout\(\(\) => \{[\s\S]*localStorage\.setItem\(`synnical-chat-messages:\$\{activeChannel\}`, JSON\.stringify\(snapshot\)\)[\s\S]*\}, 1_800\)/)
  assert.match(chat, /const renderedMessageRows = useMemo/)
})

test("r11.4 bright wallpapers keep desktop labels readable and taskbar menus anchor to their icon", () => {
  const desktop = read("src/components/desktop-shell.tsx")
  assert.match(desktop, /\[text-shadow:0_1px_2px_#000/)
  assert.doesNotMatch(desktop, /desktop[^\n]{0,200}bg-black\/65/)
  assert.match(desktop, /anchor\?: "pointer" \| "taskbar"/)
  assert.match(desktop, /anchor:"taskbar"/)
  assert.match(desktop, /transform: "translateY\(-100%\)"/)
  assert.match(desktop, /contextMenu\.y - 8/)
})



test("r11.6 desktop icons are light without losing contrast on bright wallpapers", () => {
  const desktop = read("src/components/desktop-shell.tsx")
  const shell = read("src/components/app-shell.tsx")
  assert.doesNotMatch(desktop, /rounded-xl border border-black\/25 bg-\[#111318\]\/90/)
  assert.match(desktop, /synnical-desktop-app-icon/)
  assert.match(desktop, /text-white\/90/)
  assert.match(desktop, /drop-shadow\(0 1px 1px rgba\(0,0,0,\.75\)\)/)
  assert.match(shell, /id: "movies", label: "SynnFlix", icon: Clapperboard/)
  assert.match(shell, /id: "files", label: "Synnical Files", icon: Folder/)
  assert.match(shell, /id: "settings", label: "Settings", icon: Settings/)
  assert.match(shell, /id: "youtube", label: "YouTube", icon: YouTubeIcon/)
  assert.match(shell, /id: "geforce-now", label: "GeForce NOW", icon: GeForceNowIcon/)
})

test("r11.5 Auto fullscreen uses first trusted gesture and installable fullscreen display", () => {
  const os = read("src/lib/os-settings.ts")
  const desktop = read("src/components/desktop-shell.tsx")
  const settings = read("src/components/synnical-settings-app.tsx")
  const manifest = read("src/app/manifest.ts")
  assert.match(os, /autoFullscreen: true/)
  assert.match(desktop, /window\.addEventListener\("pointerdown", enter, true\)/)
  assert.match(desktop, /window\.addEventListener\("keydown", enter, true\)/)
  assert.match(desktop, /requestFullscreen\(\{ navigationUI: "hide" \}\)/)
  assert.match(settings, /title="Auto fullscreen"/)
  assert.match(manifest, /display: "fullscreen"/)
})
